package com.paymentproject.payment.ServiceStructureImplementation;

import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Service;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;

/**
 * JWT Service
 *
 * Handles token generation, validation, and claim extraction.
 *
 * --- Bug fixed: secret key overwrite ---
 * The original code declared:
 *     private String secretkey = "123456789";
 * and then in the constructor immediately overwrote it with a freshly generated
 * key. The hardcoded value was therefore never used, but it created confusion
 * and a false sense of security. The field initializer has been removed; the
 * secret key is now sourced exclusively from application.properties (injected
 * via @Value). If the property is absent the constructor generates a random key
 * as a safe fallback for local development only — in production the property
 * must be set.
 *
 * --- Bug fixed: key signing/verification mismatch ---
 * generateToken used Keys.hmacShaKeyFor(secretkey.getBytes()) — treating the
 * Base64 string as raw UTF-8 bytes.
 * getKey used Decoders.BASE64.decode(secretkey) — correctly decoding the
 * Base64 string.
 * Because the two produced different byte arrays, any token generated by
 * generateToken would fail validation in getKey. Both paths now go through
 * getKey() consistently.
 */
@Service
public class JWTService {

    /**
     * Access token validity: 30 minutes.
     * Kept short so that stolen tokens expire quickly.
     */
    private static final long ACCESS_TOKEN_VALIDITY_MS = 1000L * 60 * 30;

    /**
     * Base64-encoded HMAC-SHA256 secret key.
     * Set this in application.properties as:
     *     security.jwt.secret-key=<base64-encoded-256-bit-key>
     * Generate a suitable value with:
     *     openssl rand -base64 32
     */
    @Value("${security.jwt.secret-key:}")
    private String secretKeyProperty;

    /**
     * The actual key used at runtime.
     * Populated once in the constructor and never changed afterward.
     */
    private String secretKey;

    /**
     * Constructor — resolves the secret key.
     *
     * If the property is blank (local dev with no config), a cryptographically
     * secure random key is generated. This means tokens do not survive application
     * restarts, which is acceptable in development but not in production.
     */
    public JWTService(@Value("${security.jwt.secret-key:}") String secretKeyProperty) {
        if (secretKeyProperty != null && !secretKeyProperty.isBlank()) {
            this.secretKey = secretKeyProperty;
        } else {
            // Fallback for local development only
            try {
                KeyGenerator keyGen = KeyGenerator.getInstance("HmacSHA256");
                SecretKey sk = keyGen.generateKey();
                this.secretKey = Base64.getEncoder().encodeToString(sk.getEncoded());
            } catch (NoSuchAlgorithmException e) {
                throw new IllegalStateException("Failed to generate JWT secret key", e);
            }
        }
    }

    /**
     * Generate a signed JWT access token for the given username.
     *
     * @param username the subject of the token
     * @return compact signed JWT string
     */
    public String generateToken(String username) {
        Map<String, Object> claims = new HashMap<>();
        return Jwts.builder()
                .setClaims(claims)
                .setSubject(username)
                .setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + ACCESS_TOKEN_VALIDITY_MS))
                .signWith(getKey(), SignatureAlgorithm.HS256)
                .compact();
    }

    /**
     * Decode the Base64 secret and return a SecretKey suitable for JWT operations.
     *
     * This is the single authoritative path for obtaining the signing key.
     * Both generateToken and validateToken use it, so they are always consistent.
     *
     * @return SecretKey derived from the configured secret
     */
    private SecretKey getKey() {
        byte[] keyBytes = Decoders.BASE64.decode(secretKey);
        return Keys.hmacShaKeyFor(keyBytes);
    }

    /**
     * Extract the username (subject claim) from a token.
     *
     * @param token signed JWT
     * @return username stored in the subject claim
     */
    public String extractUserName(String token) {
        return extractClaim(token, Claims::getSubject);
    }

    /**
     * Apply a claim extractor function to the token's claims.
     *
     * @param <T>           return type of the extractor
     * @param token         signed JWT
     * @param claimResolver function that picks one claim from the Claims map
     * @return the extracted claim value
     */
    private <T> T extractClaim(String token, Function<Claims, T> claimResolver) {
        Claims claims = extractAllClaims(token);
        return claimResolver.apply(claims);
    }

    /**
     * Parse and verify the JWT signature, returning all claims.
     *
     * If the signature is invalid or the token is malformed, the underlying JJWT
     * library throws a JwtException which propagates up to the filter layer.
     *
     * @param token signed JWT
     * @return all claims from the token payload
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parser()
                .verifyWith(getKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * Validate the token: the username must match and the token must not be
     * expired.
     *
     * @param token       signed JWT
     * @param userDetails loaded user details to compare against
     * @return true only if the token is valid for this user
     */
    public boolean validateToken(String token, UserDetails userDetails) {
        String userName = extractUserName(token);
        return userName.equals(userDetails.getUsername()) && !isTokenExpired(token);
    }

    private boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    private Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }
}
