spring.application.name=payment
spring.datasource.url=jdbc:mysql://localhost:3307/paymentschema
spring.datasource.username=root
spring.datasource.password=Rakshit05&05rakshit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name = user
spring.security.user.password = user
# Redis configuration using docker container
spring.data.redis.host=localhost
spring.data.redis.port=6379
# security.jwt.secret-key=5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA
# security.jwt.expiration-time=3600000